require "spec_helper"

RSpec.describe RuboCop::Cop::Konvenit::CommentLength, :config do
  let(:cop_config) { { "Max" => 2 } }

  it "registers an offense for a comment block longer than Max" do
    expect_offense(<<~RUBY)
      # first line
      # second line
      # third line
      ^^^^^^^^^^^^ Comment has too many lines. [3/2]
      def foo; end
    RUBY
  end

  it "registers the offense starting at the first line exceeding Max" do
    expect_offense(<<~RUBY)
      # first line
      # second line
      # third line
      ^^^^^^^^^^^^ Comment has too many lines. [4/2]
      # fourth line
      def foo; end
    RUBY
  end

  it "accepts a comment block with Max lines" do
    expect_no_offenses(<<~RUBY)
      # first line
      # second line
      def foo; end
    RUBY
  end

  it "accepts comment blocks separated by an empty line" do
    expect_no_offenses(<<~RUBY)
      # first line
      # second line

      # third line
      def foo; end
    RUBY
  end

  it "treats comments with different indentation as separate blocks" do
    expect_no_offenses(<<~RUBY)
      # first line
      # second line
      def foo
        # third line
        bar
      end
    RUBY
  end

  it "registers an offense for an indented comment block" do
    expect_offense(<<~RUBY)
      def foo
        # first line
        # second line
        # third line
        ^^^^^^^^^^^^ Comment has too many lines. [3/2]
        bar
      end
    RUBY
  end

  it "ignores trailing comments" do
    expect_no_offenses(<<~RUBY)
      a = 1 # first
      b = 2 # second
      c = 3 # third
    RUBY
  end

  it "ignores magic comments and rubocop directives" do
    expect_no_offenses(<<~RUBY)
      # frozen_string_literal: true
      # rubocop:disable Style/Foo
      # first line
      # second line
      def foo; end
    RUBY
  end

  it "ignores schema blocks generated by annotate" do
    expect_no_offenses(<<~RUBY)
      # == Schema Information
      #
      # Table name: users
      #
      class User; end
    RUBY
  end

  context "with Max: 1" do
    let(:cop_config) { { "Max" => 1 } }

    it "registers an offense for a two line comment" do
      expect_offense(<<~RUBY)
        # first line
        # second line
        ^^^^^^^^^^^^^ Comment has too many lines. [2/1]
        def foo; end
      RUBY
    end
  end
end
